name: marshather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_img: ^0.0.3
  flutter_screenutil: ^5.7.0
  flutter_slidable_panel: ^1.1.1
  flutter_statusbarcolor_ns: ^0.5.0
  get_it: ^7.6.4
  go_router: ^10.0.0
  google_fonts: ^4.0.4
  gradient_like_css: ^1.0.1
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  vibration: ^1.8.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/